/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author paolovargas1
 */
public class MInterface extends javax.swing.JFrame {

    /**
     * Creates new form MInterface
     */
    public MInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoutejTextArea = new javax.swing.JTextArea();
        PricejLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        DepBjComboBox = new javax.swing.JComboBox<>();
        DestAjComboBox = new javax.swing.JComboBox<>();
        DestBjComboBox = new javax.swing.JComboBox<>();
        DepartureField = new javax.swing.JLabel();
        DestinationLabel = new javax.swing.JLabel();
        DepAjComboBox = new javax.swing.JComboBox<>();
        DeparturejTextField = new javax.swing.JTextField();
        DestinationjTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        RouteButton = new javax.swing.JButton();
        RoutejLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Map");

        RoutejTextArea.setColumns(20);
        RoutejTextArea.setRows(5);
        jScrollPane1.setViewportView(RoutejTextArea);

        PricejLabel.setText("Price");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        DepBjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", " " }));
        DepBjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepBjComboBoxActionPerformed(evt);
            }
        });

        DestAjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", " " }));
        DestAjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestAjComboBoxActionPerformed(evt);
            }
        });

        DestBjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", " " }));
        DestBjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestBjComboBoxActionPerformed(evt);
            }
        });

        DepartureField.setText("Departure:");

        DestinationLabel.setText("Destination:");

        DepAjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", " " }));
        DepAjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepAjComboBoxActionPerformed(evt);
            }
        });

        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        SearchButton.setText("search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        RouteButton.setText("route");
        RouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RouteButtonActionPerformed(evt);
            }
        });

        RoutejLabel.setText("Route");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(RoutejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DepartureField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DeparturejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DepAjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DepBjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DestinationLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DestinationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DestAjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DestBjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RouteButton))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(PricejLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartureField)
                    .addComponent(DestinationLabel)
                    .addComponent(DepAjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeparturejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestinationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepBjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestAjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestBjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoutejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(PricejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepBjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepBjComboBoxActionPerformed
        String selectedLine = DepBjComboBox.getSelectedItem().toString();
        DeparturejTextField.setText(selectedLine);
    }//GEN-LAST:event_DepBjComboBoxActionPerformed

    private void DestAjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestAjComboBoxActionPerformed
        String selectedLine = DestAjComboBox.getSelectedItem().toString();
        DestinationjTextField.setText(selectedLine);
    }//GEN-LAST:event_DestAjComboBoxActionPerformed

    private void DestBjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestBjComboBoxActionPerformed
        String selectedLine = DestBjComboBox.getSelectedItem().toString();
        DestinationjTextField.setText(selectedLine);
    }//GEN-LAST:event_DestBjComboBoxActionPerformed

    private void DepAjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepAjComboBoxActionPerformed
        String selectedLine = DepAjComboBox.getSelectedItem().toString();
        DeparturejTextField.setText(selectedLine);
    }//GEN-LAST:event_DepAjComboBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        DeparturejTextField.setText(" ");
        DestinationjTextField.setText(" ");
        RoutejTextArea.setText(" ");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        RoutejTextArea.setText(" ");
        SuperClassBus Bus = new SuperClassBus();
        SubDeparture R1 = new SubDeparture();
        SubDestination R2 = new SubDestination();

        boolean CheckLF=false;
        boolean CheckSF=false;
        boolean CheckLT=false;
        boolean CheckST=false;

        ArrayList<Integer> R = new ArrayList<>();
        String A = DestinationjTextField.getText();
        String B = DeparturejTextField.getText();

        if (A == null || B == null){

            Messages.BusNotFoundMessage();
            DestinationjTextField.setText(" ");
            DeparturejTextField.setText(" ");

        }else{

            String Line = InputManage.SplitLine(A);
            int Stop = InputManage.SplitStop(A);
            String LineT = InputManage.SplitLine(B);
            int StopT = InputManage.SplitStop(B);

            if (Line == null || LineT == null || StopT == 0 || Stop == 0 ) {

                Messages.BusNotFoundMessage();
                DestinationjTextField.setText(" ");
                DeparturejTextField.setText(" ");
            }else

            CheckLF = Bus.CheckLines(Line);
            CheckSF = Bus.CheckStops(Stop);
            CheckLT = Bus.CheckLines(LineT);
            CheckST = Bus.CheckStops(StopT);

            if (CheckLT == true & CheckST == true & CheckLF == true & CheckSF == true){

                Messages.SearchConfirmationMessage();
                R1.setFromLine(Line);
                R1.setFromStop(Stop);
                R2.setToLine(LineT);
                R2.setToStop(StopT);

            }else {
                Messages.BusNotFoundMessage();
                DestinationjTextField.setText(" ");
                DeparturejTextField.setText(" ");
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void RouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RouteButtonActionPerformed
        ArrayList<Integer> R = new ArrayList<>();
        ArrayList<Integer> R2 = new ArrayList<>();
        String A = DeparturejTextField.getText();
        String B = DestinationjTextField.getText();

        String Line = InputManage.SplitLine(A);
        int Stop = InputManage.SplitStop(A);
        String LineT = InputManage.SplitLine(B);
        int StopT = InputManage.SplitStop(B);

        if (Line.equals(LineT)){ //  if the departure and destination Lines are the same

            if (Stop<StopT){ // if my Departure point ins BEFORE Destination
                R = RouteDisplay.GetRoute(Stop,StopT);
                for (int i = 0 ; i<R.size() ; i++){
                    RoutejTextArea.append(Line + R.get(i)+" -->");
                    if ( i == 5 ){
                        RoutejTextArea.append("\n");
                    }
                }
            }else { // if my Departure point ins AFTER Destination
                R = RouteDisplay.GetRoute2(StopT,Stop);
                for (int i = 0 ; i<R.size() ; i++){
                    RoutejTextArea.append(Line + R.get(i)+ "-->");
                    if ( i == 5 ){
                        RoutejTextArea.append("\n");
                    }
                }
            }
        }else{
            if (Line.equals("A") && LineT.equals("B")){ // if Depar = A   & Dest = B
                R = RouteDisplay.GetRouteTA(Stop);
                for ( int i: R){
                    RoutejTextArea.append(Line + i + "-->");
                    if ( i == 5 ){
                        RoutejTextArea.append("\n");
                    }
                }
                int e = R.get(R.size()-1); // Get the value of the last element in the ArrayList 'R'
                R2 = RouteDisplay.GetRouteT(StopT,e);
                Collections.reverse(R2);
                RoutejTextArea.append("\n");
                RoutejTextArea.append("=== TRANSFER === "+ "["+ Line + R.get(R.size()-1)+"-->"+ LineT +R2.get(0)+"]");
                RoutejTextArea.append("\n");
                for (int i: R2){
                    RoutejTextArea.append(LineT + i + "-->");
                    if ( i == 5 ){
                        RoutejTextArea.append("\n");
                    }
                }

            }else if (Line.equals("B") && LineT.equals("A")) { // if Depar = B   & Dest = A
                R = RouteDisplay.GetRouteTB(Stop);
                for ( int i: R){
                    RoutejTextArea.append(Line + i + "-->");
                    if ( i == 5 ){
                        RoutejTextArea.append("\n");
                    }
                }
                RoutejTextArea.append("\n");
                RoutejTextArea.append("-->-->-->-->-->-->");
                RoutejTextArea.append("\n");
                int e = R.get(R.size()-1);
                R2 = RouteDisplay.GetRouteT(StopT,e);
                Collections.reverse(R2);
                for (int i: R2) {
                    RoutejTextArea.append(LineT + i + "-->");
                    if ( i == 5 ){
                        RoutejTextArea.append("\n");
                    }
                }
            }
        }
    }//GEN-LAST:event_RouteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DepAjComboBox;
    private javax.swing.JComboBox<String> DepBjComboBox;
    private javax.swing.JLabel DepartureField;
    private javax.swing.JTextField DeparturejTextField;
    private javax.swing.JComboBox<String> DestAjComboBox;
    private javax.swing.JComboBox<String> DestBjComboBox;
    private javax.swing.JLabel DestinationLabel;
    private javax.swing.JTextField DestinationjTextField;
    private javax.swing.JLabel PricejLabel;
    private javax.swing.JButton RouteButton;
    private javax.swing.JLabel RoutejLabel;
    private javax.swing.JTextArea RoutejTextArea;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
