/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Register;


import Login.Login;
import Connection.DBConnection;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author paolovargas1
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }
        public boolean CheckUsername(String username) {
            
            DBConnection con = new DBConnection();
            Connection reg = con.getConnection();
            ResultSet rs;
            boolean checkUser = false;
            String query = "select*from Registration where username=?";
            
            try {
                
                PreparedStatement ps = reg.prepareStatement(query);
                
                ps.setString(1,username);
                rs = ps.executeQuery();
                
            
                if (rs.next()){ // means that if the next row is not null (means if it exist)
                    checkUser=true;
                }
            }catch (SQLException e){
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE,null,e);
                
            }
            return checkUser;
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RConfPasswordField1 = new javax.swing.JPasswordField();
        RUsernamejTextField = new javax.swing.JTextField();
        ConfPasswordjLabel = new javax.swing.JLabel();
        RFormjLabel = new javax.swing.JLabel();
        EmailjLabel = new javax.swing.JLabel();
        RMinimizejLabel = new javax.swing.JLabel();
        EmailjTextField = new javax.swing.JTextField();
        RExitjLabel = new javax.swing.JLabel();
        CellphonejLabel = new javax.swing.JLabel();
        FirstNamejLabel = new javax.swing.JLabel();
        CellphonejTextField = new javax.swing.JTextField();
        LastNamejLabel = new javax.swing.JLabel();
        RclearjButton = new javax.swing.JButton();
        FirstNamejTextField = new javax.swing.JTextField();
        registerjButton = new javax.swing.JButton();
        LastNamejTextField = new javax.swing.JTextField();
        toLoginjLabel = new javax.swing.JLabel();
        RUsernamejLabel = new javax.swing.JLabel();
        RPasswordField = new javax.swing.JPasswordField();
        RPasswordjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RUsernamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUsernamejTextFieldActionPerformed(evt);
            }
        });

        ConfPasswordjLabel.setText("Confirm Password:");

        RFormjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        RFormjLabel.setText("Register Form");

        EmailjLabel.setText("E-mail:");

        RMinimizejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        RMinimizejLabel.setText("-");
        RMinimizejLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RMinimizejLabelMouseClicked(evt);
            }
        });

        EmailjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailjTextFieldActionPerformed(evt);
            }
        });

        RExitjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        RExitjLabel.setText("X");
        RExitjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RExitjLabelMouseClicked(evt);
            }
        });

        CellphonejLabel.setText("Cellphone Number:");

        FirstNamejLabel.setText("First Name:");

        CellphonejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CellphonejTextFieldActionPerformed(evt);
            }
        });

        LastNamejLabel.setText("Last Name:");

        RclearjButton.setText("clear");
        RclearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RclearjButtonActionPerformed(evt);
            }
        });

        FirstNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNamejTextFieldActionPerformed(evt);
            }
        });

        registerjButton.setText("register");
        registerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerjButtonActionPerformed(evt);
            }
        });

        LastNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNamejTextFieldActionPerformed(evt);
            }
        });

        toLoginjLabel.setText("click to Login -->");
        toLoginjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toLoginjLabelMouseClicked(evt);
            }
        });

        RUsernamejLabel.setText("Username:");

        RPasswordjLabel.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(RFormjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RMinimizejLabel)
                .addGap(18, 18, 18)
                .addComponent(RExitjLabel)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RPasswordjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(RPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CellphonejLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CellphonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FirstNamejLabel)
                            .addComponent(LastNamejLabel)
                            .addComponent(RUsernamejLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RUsernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ConfPasswordjLabel)
                            .addComponent(EmailjLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RConfPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(RclearjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(toLoginjLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RFormjLabel)
                    .addComponent(RExitjLabel)
                    .addComponent(RMinimizejLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNamejLabel)
                    .addComponent(FirstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNamejLabel)
                    .addComponent(LastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RUsernamejLabel)
                    .addComponent(RUsernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RPasswordjLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfPasswordjLabel)
                    .addComponent(RConfPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailjLabel)
                    .addComponent(EmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CellphonejLabel)
                    .addComponent(CellphonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RclearjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(toLoginjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RUsernamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUsernamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RUsernamejTextFieldActionPerformed

    private void RMinimizejLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMinimizejLabelMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_RMinimizejLabelMouseClicked

    private void EmailjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailjTextFieldActionPerformed

    private void RExitjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RExitjLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_RExitjLabelMouseClicked

    private void CellphonejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CellphonejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CellphonejTextFieldActionPerformed

    private void FirstNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNamejTextFieldActionPerformed

    private void registerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerjButtonActionPerformed
        DBConnection con = new DBConnection();
        Connection reg = con.getConnection();

        String firstN = FirstNamejTextField.getText();
        String lastN = LastNamejTextField.getText();
        String userN = RUsernamejTextField.getText();
        String pass = String.valueOf(RPasswordField.getPassword());
        String confpass =  String.valueOf(RConfPasswordField1.getPassword());
        String email = EmailjTextField.getText();
        String cellphone = CellphonejTextField.getText();

        if (firstN.equals(" ")){
            JOptionPane.showMessageDialog(null, "Enter First Name");
        }
        else if (lastN.equals(" ")){
            JOptionPane.showMessageDialog(null, "Enter Last Name");
        }
        else if (pass.equals(" ") || confpass.equals(" ")) {
            JOptionPane.showMessageDialog(null, "Enter Password");
        }
        else if (!pass.equals(confpass)){
            JOptionPane.showMessageDialog(null, "Please Re-Enter Password");
            RPasswordField.setText(" ");
            RConfPasswordField1.setText(" ");
        }
        else if (CheckUsername(userN) == true ){
            JOptionPane.showMessageDialog(null, "Username Alredy exists");
            RUsernamejTextField.setText(" ");
        }
        else {
            PreparedStatement ps;
            String query = "insert into  Registration values (?,?,?,?,?,?) ";
        
                try {
                    ps = reg.prepareStatement(query);
                    ps.setString(1,firstN);
                    ps.setString(2,lastN);
                    ps.setString(3,userN);
                    ps.setString(4,pass);
                    ps.setString(5,email);
                    ps.setString(6,cellphone);
                    
                    
                    if  (ps.executeUpdate()>0){
                        JOptionPane.showMessageDialog(null," New User Added ! ");
                    }
                    FirstNamejTextField.setText("");
                    LastNamejTextField.setText("");
                    RUsernamejTextField.setText("");
                    RPasswordField.setText("");
                    RConfPasswordField1.setText("");
                    EmailjTextField.setText("");
                    CellphonejTextField.setText("");

                } catch (SQLException ex) {
                    Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            
        }
    }//GEN-LAST:event_registerjButtonActionPerformed

    private void LastNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNamejTextFieldActionPerformed

    private void toLoginjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toLoginjLabelMouseClicked
        Login lgf = new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_toLoginjLabelMouseClicked

    private void RclearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RclearjButtonActionPerformed
        // TODO add your handling code here:
        FirstNamejTextField.setText(" ");
        LastNamejTextField.setText(" ");
        RUsernamejTextField.setText("");
        RPasswordField.setText("");
        RConfPasswordField1.setText("");
        EmailjTextField.setText(" ");
        CellphonejTextField.setText(" ");

    }//GEN-LAST:event_RclearjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CellphonejLabel;
    private javax.swing.JTextField CellphonejTextField;
    private javax.swing.JLabel ConfPasswordjLabel;
    private javax.swing.JLabel EmailjLabel;
    private javax.swing.JTextField EmailjTextField;
    private javax.swing.JLabel FirstNamejLabel;
    private javax.swing.JTextField FirstNamejTextField;
    private javax.swing.JLabel LastNamejLabel;
    private javax.swing.JTextField LastNamejTextField;
    private javax.swing.JPasswordField RConfPasswordField1;
    private javax.swing.JLabel RExitjLabel;
    private javax.swing.JLabel RFormjLabel;
    private javax.swing.JLabel RMinimizejLabel;
    private javax.swing.JPasswordField RPasswordField;
    private javax.swing.JLabel RPasswordjLabel;
    private javax.swing.JLabel RUsernamejLabel;
    private javax.swing.JTextField RUsernamejTextField;
    private javax.swing.JButton RclearjButton;
    private javax.swing.JButton registerjButton;
    private javax.swing.JLabel toLoginjLabel;
    // End of variables declaration//GEN-END:variables
}
